package_rename_config:
  android:
    kim_hue_thao_bank: kim_hue_thao_bank
    package_name: com.kim_hue_thao_bank.kim_hue_thao_bank
    lang: kotlin

  ios:
    kim_hue_thao_bank: kim_hue_thao_bank
    bundle_name: kim_hue_thao_bank
    package_name: com.kim_hue_thao_bank.kim_hue_thao_bank