package_rename_config:
  android:
    AppName: AppName
    package_name: com.AppName.AppName
    lang: kotlin

  ios:
    AppName: AppName
    bundle_name: AppName
    package_name: com.AppName.AppName